name: CorePC Native Kernel CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-2022

    strategy:
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, ARM64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{matrix.build_configuration}} 
        -A ${{matrix.build_platform}}

    - name: Build CorePC Binary Targets
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_configuration}}

    - name: Run CorePC Regression Unit Tests
      run: ctest --test-dir ${{github.workspace}}/build -C ${{matrix.build_configuration}} --output-on-failure
